plugins {
	id 'maven-publish'
}

def isModernMinecraft = stonecutter.eval(stonecutter.current.version, '>=26.1')
apply plugin: isModernMinecraft ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'

version = "${project.mod_version}+${stonecutter.current.version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url 'https://maven.terraformersmc.com/releases/' }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	if (!isModernMinecraft) {
		mappings loom.officialMojangMappings()
	}

	def modConfiguration = isModernMinecraft ? 'implementation' : 'modImplementation'
	add(modConfiguration, "net.fabricmc:fabric-loader:${project.loader_version}")
	add(modConfiguration, "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")
	add(modConfiguration, "com.terraformersmc:modmenu:${project.modmenu_version}")
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'minecraft_dependency', project.minecraft_dependency
	inputs.property 'java_release', project.java_release
	inputs.property 'loader_version', project.loader_version
	inputs.property 'mixin_compatibility', project.mixin_compatibility

	filesMatching(['fabric.mod.json', 'hollower.mixins.json']) {
		expand inputs.properties
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = project.java_release.toInteger()
}

java {
	withSourcesJar()

	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}

	sourceCompatibility = JavaVersion.toVersion(project.java_release)
	targetCompatibility = JavaVersion.toVersion(project.java_release)
}

jar {
	inputs.property 'archivesName', project.base.archivesName

	from('LICENSE') {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

tasks.register('collectJars', Copy) {
	def jarTask = isModernMinecraft ? tasks.named('jar') : tasks.named('remapJar')
	dependsOn jarTask
	from jarTask
	into rootProject.layout.buildDirectory.dir('libs')
}

tasks.named('build') {
	finalizedBy tasks.named('collectJars')
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
}
