package com.hollower.render;

import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;

import java.util.List;

// The block ids behind HiddenBlockGroup.MISC: every decorative block the Crystal Hollows generates
// that isn't a gemstone or an ore. Kept in its own file so it doesn't bury HiddenBlockGroup's entries.
@Environment(EnvType.CLIENT)
final class MiscBlocks {
    private MiscBlocks() {
    }

    static final List<String> NAMES = List.of(
            "spruce_planks",
            "brown_terracotta",
            "spruce_fence",
            "oak_trapdoor",
            "polished_granite",
            "white_wool",
            "gravel",
            "green_wool",
            "quartz_stairs",
            "jungle_planks",
            "gray_wool",
            "glass",
            "cobblestone_slab",
            "cyan_wool",
            "stone_bricks",
            "oak_fence",
            "nether_brick_slab",
            "cobblestone_stairs",
            "infested_mossy_stone_bricks",
            "cauldron",
            "rail",
            "azure_bluet",
            "glowstone",
            "black_wool",
            "yellow_wool",
            "oak_log",
            "brown_mushroom",
            "redstone_block",
            "birch_stairs",
            "vine",
            "stone_brick_slab",
            "grass",
            "green_carpet",
            "dark_oak_slab",
            "diorite",
            "torch",
            "white_stained_glass",
            "gray_terracotta",
            "black_terracotta",
            "smooth_stone",
            "dark_oak_stairs",
            "brown_wool",
            "green_terracotta",
            "granite",
            "andesite",
            "lime_terracotta",
            "oak_sign",
            "oak_stairs",
            "obsidian",
            "blue_orchid",
            "gray_carpet",
            "orange_wool",
            "spruce_leaves",
            "red_wool",
            "gold_block",
            "oak_wood",
            "polished_diorite",
            "polished_andesite",
            "white_carpet",
            "cobblestone",
            "light_weighted_pressure_plate",
            "smooth_stone_slab",
            "quartz_block",
            "red_sandstone",
            "spruce_stairs",
            "quartz_slab",
            "chiseled_stone_bricks",
            "cyan_terracotta",
            "piston",
            "diamond_block",
            "cobblestone_wall",
            "birch_slab",
            "note_block",
            "spruce_log",
            "purple_wool",
            "large_fern",
            "skeleton_skull",
            "oak_pressure_plate",
            "stone_brick_stairs",
            "lime_wool",
            "white_terracotta",
            "light_gray_wool",
            "brewing_stand",
            "light_gray_stained_glass",
            "grass_block",
            "oak_planks",
            "tall_grass",
            "dirt",
            "light_gray_terracotta",
            "fern",
            "coarse_dirt",
            "jungle_stairs",
            "netherrack",
            "spruce_slab",
            "sea_lantern",
            "birch_fence",
            "iron_trapdoor",
            "birch_planks",
            "player_head",
            "jungle_slab",
            "red_mushroom",
            "oak_slab",
            "oak_leaves",
            "cracked_stone_bricks",
            "clay",
            "light_gray_carpet",
            "dark_oak_planks",
            "ladder",
            "fire",
            "magenta_stained_glass_pane",
            "short_grass");
}
